spring:
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: true  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix: .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 54918d1fc7f3a063

  mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml  # Mapper XML文件位置
    type-aliases-package: com.example.blog.entity  # 实体类包路径
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL日志
    global-config:
      db-config:
        logic-delete-field: deleted  # 逻辑删除字段名
        logic-delete-value: 1  # 删除时的值
        logic-not-delete-value: 0  # 未删除时的值



  logging:
    level:
      root: warn
      com.example.blog: info
    file: log/blog-pro.log

server:
  port: 8085

upload:
  path: /home/blog/uploads
